name: Go lint

on:
  push:
    branches: [ master ]
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.13 
        uses: actions/setup-go@v3
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
        
      - name: Tidy
        run: go mod tidy && [ -z "$(git status -s)" ]

      - name: Lint
        run: make lint

      - name: Vet
        run: make vet
